# Provide a name for the workflow
name: Publish Python Package

# Tell GitHub when to run the action
on:
  # This will run every time a new release is published
  release:
    types: [published]
  # Triggers the workflow on push events but only for the dist-package branch
  # Used for testing automated package publishing 
  push:
    branches: [ dist-package ]
  # This workflow can also be manually started from the Actions tab in GitHub
  workflow_dispatch:

# The publish workflow consist currently only on one job
jobs:
  publish:
    # Run the workflow on the latest Ubuntu version
    runs-on: ubuntu-latest
    permissions:
      id-token: write # NOTE: this permission is mandatory for trusted publishing
    steps:
      # Checkout pharaglow
      - name: Checkout pharaglow
        uses: actions/checkout@v3
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      # Updating pip and installing 'build'.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade build
      # Might be the pip-compile bug that keeps haunting me..
      # REF: https://github.com/jazzband/pip-tools/issues/1711
      - name: Debug action.
        run: |
          pwd
          ls -la
          echo "github workspace: ${{ github.workspace }}"
          echo "run validate-pyproject"
          python -m pip install validate-pyproject[all]
          validate-pyproject pyproject.toml
          #echo "[DEBUG] attempting to install via pip install -e ."
          #pip install -e .
          echo "installing pip-tools"
          python -m pip install pip-tools
          pip-compile --no-emit-index-url --resolver=backtracking pyproject.toml --verbose
      # Creating package wheel and a .tar.gz source distribution.
      - name: Build package
        run: >-
          python -m build
          --sdist
          --wheel
          ${{ github.workspace }}
      # Publish to TestPyPI using Trusted Publisher (GitHub)
      # REF: https://docs.pypi.org/trusted-publishers/using-a-publisher/
      # REF: https://carpentries-incubator.github.io/python_packaging/aio.html
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      # Publish to PyPI using Trusted Publisher (GitHub)
      # REF: https://docs.pypi.org/trusted-publishers/using-a-publisher/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1